# LOCALHOST CONTACTS API

### Get all contacts
GET http://localhost:3000/contacts
# Returns a JSON array of all contacts in the database.

### Get contact by id 
GET http://localhost:3000/contacts/68bf8164b34596566d6615b4


### Create a new contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Tayo",
  "lastName": "Bello",
  "email": "tybello@gmail.com",
  "favoriteColor": "Coral",
  "birthday": "1994-05-31"
}


### Update an existing contact
PUT http://localhost:3000/contacts/68c603f68d08fb81205cc169 HTTP/1.1
content-type: application/json

{ 
    "firstName": "Tayo", 
    "lastName": "Bello", 
    "email": "taybell@gmail.com", 
    "favoriteColor": "Coral", 
    "birthday": "1990-11-28" 
}

### Delete a contact
DELETE http://localhost:3000/contacts/68c603f68d08fb81205cc169

